### ISSUE TITLE
Slider focused circle and values are off

### ISSUE THREAD

**Issue by agazso** [diete-design/diete.design#146]
When showing the focused state the circle looks like it is transparent on the inside and I would expect to see the slider value going to the selected value, but this is not the case. It is a bit difficult to explain, so I made some screenshots to illustrate the issue.

50 looks OK
![gnome-shell-screenshot-e0bgqb](https://github.com/diete-design/diete.design/assets/230163/760f1207-cffa-47c3-80ea-146f187eadd0)

At 40 the value is slightly off, it does not reach the step value:
![gnome-shell-screenshot-7hmkcw](https://github.com/diete-design/diete.design/assets/230163/24dd4fd0-3c8f-4d57-8d08-27e7860f9e1f)

At 0 it looks like the slider horizontal line goes below 0. Also the circle is off-centered.
![gnome-shell-screenshot-3mnhad](https://github.com/diete-design/diete.design/assets/230163/bcca4c17-2a19-4cc0-8258-ca1eb3b3c561)

At 100 it looks as if it goes above 100. Also with three digits the popover looks of centered.
![gnome-shell-screenshot-ak4ihn](https://github.com/diete-design/diete.design/assets/230163/6c1867f8-d0c7-47b6-9ad5-107bd11feef6)

_Originally posted by @agazso in https://github.com/diete-design/diete.design/pull/71#pullrequestreview-2063509400_

**Comment by vojtechsimetka** [comment]
solved by #163
