### ISSUE TITLE
Implement Tab bar component

### ISSUE THREAD

**Issue by agazso** [diete-design/diete.design#35]
Part of #31 

As seen on https://www.figma.com/file/SIfBIOnc6qmVOJ73q42IMp/diete.design-website?type=design&node-id=4-658&mode=design&t=kAM5ID8U7rq7hLMs-4

**Comment by vojtechsimetka** [comment]
This is not really a trivial component to build as a general one. Build it with our own known values is easy (just few buttons and content that changes based on state). But generic version is quite challenging (see e.g. https://github.com/huntabyte/bits-ui/tree/main/packages/bits-ui/src/lib/bits/tabs)

The generic usage could look as follows:
```
<Tabs default="svelte">
  <Tabs.Controls>
    <Tabs.Value value="svelte">Svelte</Tabs.Value>
    <Tabs.Value value="html">Pure HTML</Tabs.Value>
  </Tabs.Controls>
  
  <Tabs.Content value="svelte">{...}</Tabs.Content>
  <Tabs.Content value="html">{...}</Tabs.Content>
</Tabs>
```

**Comment by agazso** [comment]
I can see this becoming complex quickly. I would suggest to build it first for the component page, then we can generalize it later.
